name: main
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'dev'
  pull_request:
    types: [opened, edited, synchronize, reopened]


jobs:
  build-static-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # tag=v4.1.5
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: 1.22.0
    - name: Build
      run: make build
    - name: FMT
      run: make fmt
    - name: VET
      run: make vet
    - name: LINT
      run: make lint
      env:
        LINT: true
  build-ut:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # tag=v4.1.5
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: 1.22.0
    - name: ut
      run: make test
      env:
        UT: true
